# Generated by Django 4.0.7 on 2022-10-19 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('points', models.JSONField(default=[])),
                ('user', models.CharField(max_length=256)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
    ]
