# Generated by Django 4.0.4 on 2022-07-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdata',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
