# Generated by Django 4.0.6 on 2022-08-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdata',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
