# Generated by Django 4.0.4 on 2022-08-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_mapdata_data'),
        ('map', '0002_mapdata_public'),
    ]

    operations = [
    ]
